project:
  type: website
  output-dir: docs

website:
  title: "Rachel Alvarado"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - posts.qmd
      - extracurriculars.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

