project:
  type: website
  output-dir: docs
website:
  title: "Rachel Alvarado"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Education
        menu:
          - text: "Schools Attended"
            href: education.qmd
          - text: "Coursework"
            href: coursework.qmd
      - href: posts.qmd
        text: Projects
      - href: extracurriculars.qmd
        text: Extracurriculars

format:
  html:
    theme: 
      - yeti
      - styles.scss
    toc: true
    page-layout: full

editor: visual

